image: gradle:8.6.0-jdk21-alpine

stages:
  - build
  - upload
  - release

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dhttp.proxyHost=wwwproxy.uni-muenster.de -Dhttp.proxyPort=3128 -Dhttps.proxyHost=wwwproxy.uni-muenster.de -Dhttps.proxyPort=3128 -Dhttps.nonProxyHosts=localhost,127.0.0.1,0.0.0.0,.wwu.de,.uni-muenster.de,.wwu.io,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16"

build:
  stage: build
  tags:
    - docker
  script:
    - gradle shadowJar :webapp:war :webapp:shadowJar :testdataGenerator:shadowJar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - build/libs/MREReport-Full.jar
      - webapp/build/libs/MREReport-Light.jar
      - webapp/build/libs/webapp.war
      - testdataGenerator/build/libs/MRETestdataGenerator.jar
  only:
    - master
    - tags

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      PACKAGE_REGISTRY_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}"
      echo curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build/libs/MREReport-Full.jar ${PACKAGE_REGISTRY_URL}/MREReport-${CI_COMMIT_TAG}-Full.jar
    - |
      PACKAGE_REGISTRY_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}"
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build/libs/MREReport-Full.jar ${PACKAGE_REGISTRY_URL}/MREReport-${CI_COMMIT_TAG}-Full.jar


release_job:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  rules:
    - if: $CI_COMMIT_TAG  
  needs:
    - job: build
      artifacts: true
  script:
    - PACKAGE_REGISTRY_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}"
    - export PACKAGE_REGISTRY_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}"
  release:
    name: "Auto-Release $CI_COMMIT_SHORT_SHA"
    description: "Automatic created release $CI_COMMIT_TITLE"
    tag_name: "$CI_COMMIT_SHORT_SHA"
    assets:
      links:
        - name: MREReport-${CI_COMMIT_TAG}-Full.jar
          url: ${PACKAGE_REGISTRY_URL}/MREReport-${CI_COMMIT_TAG}-Full.jar





