image: gradle:7.4.2-jdk11-alpine

stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dhttp.proxyHost=wwwproxy.uni-muenster.de -Dhttp.proxyPort=3128 -Dhttps.proxyHost=wwwproxy.uni-muenster.de -Dhttps.proxyPort=3128 -Dhttps.nonProxyHosts=localhost,127.0.0.1,0.0.0.0,.wwu.de,.uni-muenster.de,.wwu.io,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16"

build:
  stage: build
  tags:
    - docker
  script:
    - gradle shadowJar :webapp:war :webapp:shadowJar :testdataGenerator:shadowJar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - build/libs/MREReport-Full.jar
      - webapp/build/libs/MREReport-Light.jar
      - webapp/build/libs/webapp.war
      - testdataGenearator/build/libs/MDTestdataGenerator.jar
  only:
    - main




