name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew shadowJar
      - name: Get artifact path
        id: get-artifact
        run: echo "::set-output name=jar_name::$(ls build/libs | grep -E '.*-all.jar$')"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: shadow-jar
          path: build/libs/${{ steps.get-artifact.outputs.jar_name }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/${{ steps.get-artifact.outputs.jar_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}